# Generated by Django 5.2.8 on 2025-11-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransaction',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
