# Generated by Django 5.2.8 on 2025-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0003_alter_personaltransaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=7),
        ),
    ]
