# Generated by Django 5.2.8 on 2025-11-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0005_category_user_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
