# Generated by Django 5.2.8 on 2026-04-27 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0006_remove_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кошелька')),
                ('wallet_type', models.CharField(choices=[('debet', 'Дебетовая'), ('credit', 'Кредитная'), ('crypto', 'Криптокошелек'), ('saving', 'Накопительный счет')], default='debet', max_length=15, verbose_name='Тип счета')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=6, verbose_name='Тип валюты')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.AddField(
            model_name='personaltransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='personal_finance.wallet', verbose_name='Счет'),
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма перевода')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перевода')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='personal_finance.wallet', verbose_name='Откуда')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='personal_finance.wallet', verbose_name='Куда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перевод между счетами',
                'verbose_name_plural': 'Переводы между счетами',
            },
        ),
    ]
