# Generated by Django 5.2.8 on 2026-04-27 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0007_alter_personaltransaction_total_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_wallet_per_user'),
        ),
        migrations.AddConstraint(
            model_name='wallettransfer',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_wallet_transfer_user_idempotency_key'),
        ),
    ]
