# Generated by Django 5.2.8 on 2026-04-28 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0008_alter_wallet_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_wallet_name_per_user'),
        ),
    ]
