# Generated by Django 5.2.8 on 2026-05-01 13:06

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('personal_finance', 'Category')

    initial_categories = [
        {'name': 'Продукты', 'type': 'expense'},
        {'name': 'Транспорт', 'type': 'expense'},
        {'name': 'Жилье и ЖКХ', 'type': 'expense'},
        {'name': 'Развлечения', 'type': 'expense'},
        {'name': 'Здоровье', 'type': 'expense'},
        {'name': 'Связь и интернет', 'type': 'expense'},
        {'name': 'Зарплата', 'type': 'income'},
        {'name': 'Фриланс', 'type': 'income'},
        {'name': 'Перевод', 'type': 'income'},
        {'name': 'Кэшбэк', 'type': 'income'},
    ]

    for cat in initial_categories:
        Category.objects.get_or_create(
            name=cat['name'],
            category_type=cat['type'],
            user=None,
            defaults={'is_active': True}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0010_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
