# Generated by Django 5.2.8 on 2026-05-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0011_auto_20260501_1606'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнено'),
        ),
        migrations.CreateModel(
            name='WalletMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('member', 'Участник')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отключен')], db_index=True, default='active', max_length=10)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_member_invites_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_memberships', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='personal_finance.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wallet', 'user'), name='uniq_wallet_member_wallet_user')],
            },
        ),
        migrations.CreateModel(
            name='WalletShareInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_share_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_share_received', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_invites', to='personal_finance.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('wallet', 'to_user'), name='uniq_pending_wallet_invite')],
            },
        ),
    ]
