# Generated by Django 5.2.8 on 2026-05-05 11:45

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('personal_finance', '0011_auto_20260501_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='post',
            name='linked_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='personal_finance.category', verbose_name='Связанная категория'),
        ),
    ]
