# Generated by Django 5.2.8 on 2026-05-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_unreviewed_changes',
            field=models.BooleanField(default=False, verbose_name='Есть непроверенные изменения'),
        ),
        migrations.AddField(
            model_name='post',
            name='pending_revision',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ожидающие правки'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('checking', 'На проверке'), ('published', 'Опубликовано')], default='draft', max_length=50, verbose_name='Статус'),
        ),
    ]
