# Generated by Django 5.2.8 on 2026-05-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
        ('personal_finance', '0012_personaltransaction_performed_by_walletmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_contributions', to='personal_finance.wallet', verbose_name='Счет списания'),
        ),
    ]
