# Generated by Django 5.2.8 on 2026-06-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_goalcontribution_wallet'),
        ('personal_finance', '0013_categorylimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcontribution',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_contributions', to='personal_finance.wallet', verbose_name='Счет списания'),
        ),
    ]
